### ISSUE TITLE
Unable to get the nuget version working for Projectables with UseMemberBody

### ISSUE THREAD

**Issue by brezina1** [koenbeuk/EntityFrameworkCore.Projectables#99] opened 2024-02-07 13:15 UTC
I was trying to track down an issue where using a Projectable property with backing field never loads the value. I figured out that it works as expected when I reference the `EntityFrameworkCore.Projectables` and `EntityFrameworkCore.Projectables.Generator` projects as it's done in the `BasicSample` project. The `BasicSample` project features the following code:
```
[Projectable(UseMemberBody = nameof(_FullName))]
public string FullName { get; set; }
private string _FullName => FirstName + " " + LastName;
```
While running the `BasicSample` with the Projectables projects referenced the console output is the following:

<details>
<summary>Console output from BasicSample with dirrect project references</summary>

User name: Jon Doe
User name: Jon Doe
User name: Jon Doe
User name: Jon Doe
Our first user Jon Doe has spent 5,7
Our first user Jon Doe has spent 5,7
Our users combined spent: 5,7
Our user (Jon Doe) spent 5,7
Our users spent 5,7 on its biggest order
Our users bought the following products starting with 'Red': Red pen
User name: Jon Doe, Orders: Red pen, Blue pen

</details>

After removing the project references and instead adding the nuget equivalents - `EntityFrameworkCore.Projectables 3.0.4` and `EntityFrameworkCore.Projectables.Abstractions 3.0.4` to the `BasicSample` project and running it, the before mentioned `FullName` property (and others) stop working. Here is the console output:

<details>
<summary>Console output from BasicSample with nuget references</summary>

User name:
User name:
User name:
User name:
Our first user  has spent 0
Our first user  has spent 0
Our users combined spent: 5,7
Our user (Jon Doe) spent 5,7
Our users spent 5,7 on its biggest order
Our users bought the following products starting with 'Red': Red pen
User name: , Orders: Red pen, Blue pen

</details>

I also tried different nuget versions with no luck, so I might just be doing something wrong.

**Comment by koenbeuk** [comment] 2024-03-08 01:09
This issue would have been caused by #86, which was fixed in the latest master branch but not yet in v3.0.4. Please give v4.0.0-preview.1 a chance and let me know if this is still an issue there.

**Closed by koenbeuk** 2024-03-08 01:09 UTC
Labels: bug
